### ISSUE TITLE
스프링 스케줄러 서버에서 AWS NAT를 통해 스프링 API 서버로 통신하여, 불필요한 네트워크 비용 부과

### ISSUE THREAD

**Issue by JMsuper** [JMsuper/java-bondtypestock-investment-strategy#27]
``` yml
cache:
  server:
    url-1: https://snowball-stock.site/api/v1/finances/screening
    url-2: https://snowball-stock.site/api/v1/finances/stocks
```
application.yml 內 url 도메인을 private ip 로 변경 필요

- 도메인으로 API 호출 시 NAT Gateway(10.10.0.174)를 통해 API 서버 연결됨

![image](https://github.com/user-attachments/assets/1a1cbc40-226e-4eba-8f16-e978fb33a90f)

- private ip 로 traceroute 시 NAT 경유하지 않음

![image](https://github.com/user-attachments/assets/15749e0e-b705-4513-8eaa-bc71a87530b6)

보안그룹에 ICMP 를 허용하지 않아 패킷에 응답하지는 않음

**Comment by JMsuper** [comment]
#### perplexity.ai - 도커 컨테이너와 관련하여, host os의 /etc/hosts에 ip주소와 도메인명을 지정하면 이는 도커 컨테이너가 도메인에 대한 ip 주소를 찾을 때 적용되는가?

도커 컨테이너는 기본적으로 호스트 OS의 /etc/hosts 파일을 상속받지 않습니다. 따라서 호스트 OS의 /etc/hosts에 IP 주소와 도메인명을 지정하더라도 도커 컨테이너에서는 자동으로 적용되지 않습니다

그러나 도커 컨테이너에서 호스트의 /etc/hosts 항목을 사용할 수 있는 몇 가지 방법이 있습니다:

1. --add-host 옵션 사용: 컨테이너를 실행할 때 --add-host 옵션을 사용하여 호스트 항목을 추가할 수 있습니다

2. Docker Compose 사용: docker-compose.yml 파일에 extra_hosts 섹션을 추가하여 호스트 항목을 지정할 수 있습니다

3. 로컬 DNS 캐시 사용: 호스트에서 로컬 DNS 캐시(예: dnsmasq)를 실행하고 /etc/hosts를 참조하도록 구성할 수 있습니다

4. 컨테이너 시작 시 /etc/hosts 수정: 컨테이너의 엔트리포인트 스크립트에서 /etc/hosts 파일을 동적으로 수정할 수 있습니다

결론적으로, 호스트 OS의 /etc/hosts 파일은 도커 컨테이너에 자동으로 적용되지 않지만, 위의 방법들을 통해 컨테이너에서 호스트의 DNS 설정을 사용할 수 있습니다.

**Comment by JMsuper** [comment]
API 서버와 통신하는 목적은 Nginx의 API 응답 캐싱을 업데이트하기 위함이다.

API 호출 시 HTTP 헤더의 cache-control 을 'no-cache'로 지정하여, 

뒷 단의 어플리케이션 서버로 부터 신규 응답을 가져오도록 한다.

현재 Nginx는 HTTP, HTTPS 를 지원하지만, HTTP 요청시 HTTPS(443) 으로 redirect 하도록 설정되어 있다.

IP 주소로 API 요청시(ex. curl https://10.10.*.*:443/api/v1/~~) "10.10.*.*" 에 대한 SSL 인증서를 확인하지 못하므로,

도메인(snowball-stock.site)을 통해야만 HTTPS 통신이 이뤄질 수 있다.

위 도메인은 Spring 서버에서 고정적으로 계속 사용될 예정이므로, 불필요한 DNS query를 방지해야 한다.

이를 위해, perplexity가 답변 준 "**docker-compose.yml 파일에 extra_hosts 섹션을 추가하여 호스트 항목을 지정**"을 사용한다.

**Comment by JMsuper** [comment]
#### docker-compose 변경사항(예시)
```
version: '3'
services:
  your_service_name:
    image: your_image
    extra_hosts:
      - "example.com:192.168.1.100"
      - "another-example.com:192.168.1.101"
```

#### private subnet & ec2 & springboot -> public subnet & ec2 & nginx 연결 경로 변경
- 변경 전 traceroute : **AWS NAT 경유 O**
![image](https://github.com/user-attachments/assets/1a1cbc40-226e-4eba-8f16-e978fb33a90f)
- 변경 후 traceroute : **AWS NAT 경유 X**
![image](https://github.com/user-attachments/assets/c95294c2-6fde-424f-b93f-11411fe91f75)

#### 기대효과
![image](https://github.com/user-attachments/assets/2bc21c53-f5ea-453d-958b-cec7865dcebb)

NAT 비용 줄이기
