### ISSUE TITLE
Grafana Alert Rule 적용 - Slack 연동

### ISSUE THREAD

**Issue by JMsuper** [JMsuper/java-bondtypestock-investment-strategy#29]
#### **Spring 애플리케이션**

- **높은 응답 시간**: 응답 시간이 500ms를 초과할 경우 알림
- **JVM 힙 메모리 사용량**: 힙 메모리 사용률이 80%를 초과할 경우 알림

#### **NGINX**

- **낮은 요청 처리율**: 초당 요청 처리 수가 평소보다 30% 이상 감소할 경우 알림

#### **Redis**

- **낮은 키 히트율**: 키 히트율이 50% 미만으로 떨어질 경우 알림

#### **MySQL**

- **느린 쿼리 발생**: 10초 이상 걸리는 쿼리가 발생할 경우 알림
- **높은 연결 수**: 활성 연결 수가 최대 연결 수의 80%를 초과할 경우 알림

#### **EC2 (Linux)**

- **높은 CPU 사용률**: CPU 사용률이 90%를 초과할 경우 알림
- **높은 디스크 사용률**: 디스크 사용률이 85%를 초과할 경우 알림
- **높은 메모리 사용률**: 메모리 사용률이 90%를 초과할 경우 알림
- **높은 네트워크 트래픽**: 네트워크 I/O가 평소보다 50% 이상 증가할 경우 알림

**Comment by JMsuper** [comment]
![image](https://github.com/user-attachments/assets/1f631650-b276-4601-9d96-6d2e44279009)

**Comment by JMsuper** [comment]
### Grafana -Rules Code
``` yml
apiVersion: 1
groups:
    - orgId: 1
      name: nginx
      folder: nginx
      interval: 1m
      rules:
        - uid: ce8nwnqw5ccn4e
          title: '낮은 요청 처리율: 초당 요청 처리 수가 평소보다 30% 이상 감소'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: rate(nginx_http_requests_total[5m]) / avg_over_time(rate(nginx_http_requests_total[1h])[5m:])
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 7
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
    - orgId: 1
      name: mysql
      folder: mysql
      interval: 1m
      rules:
        - uid: de8nxdixn9lhcf
          title: '느린 쿼리 발생: 10초 이상 걸리는 쿼리가 발생'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: increase(mysql_global_status_slow_queries[5m])
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
        - uid: ce8nxh9p91uyoa
          title: '높은 연결 수: 활성 연결 수가 최대 연결 수의 80%를 초과'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: mysql_global_status_threads_connected / mysql_global_variables_max_connections * 100
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
    - orgId: 1
      name: linux
      folder: linux
      interval: 1m
      rules:
        - uid: fe8nxm0eqqoe8a
          title: '높은 CPU 사용률: CPU 사용률이 90%를 초과'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
        - uid: ce8nxqhkledc0c
          title: '높은 디스크 사용률: 디스크 사용률이 80%를 초과'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"})
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 81
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
        - uid: be8nxt4vkxjb4a
          title: '높은 메모리 사용률: 메모리 사용률이 90%를 초과'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
        - uid: ae8nyqz9az7r4d
          title: '높은 네트워크 트래픽: 네트워크 I/O가 평소보다 50% 이상 증가'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: "rate(node_network_transmit_bytes_total{device=\"eth0\"}[10m]) / \r\navg_over_time(rate(node_network_transmit_bytes_total{device=\"eth0\"}[1h])[10m:])"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1.5
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
    - orgId: 1
      name: springboot
      folder: springboot
      interval: 1m
      rules:
        - uid: ae8nv5a7ok64ga
          title: '높은 응답 시간: 응답 시간이 500ms를 초과'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: "rate(http_server_requests_seconds_sum{job=\"spring-api\"}[5m]) / rate(http_server_requests_seconds_count{job=\"spring-api\"}[5m])\r\n"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
        - uid: de8nw3p4d2h34a
          title: 'JVM 힙 메모리 사용량: 힙 메모리 사용률이 80%를 초과'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: "(\r\n  jvm_memory_used_bytes{area=\"heap\", job=\"spring-api\"} / \r\n  ignoring(area) jvm_memory_max_bytes{area=\"heap\", job=\"spring-api\"}\r\n) * 100\r\n\r\nor\r\n\r\n(\r\n  jvm_memory_used_bytes{area=\"heap\", job=\"spring-scheduler\"} / \r\n  ignoring(area) jvm_memory_max_bytes{area=\"heap\", job=\"spring-scheduler\"}\r\n) * 100 "
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 80
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
    - orgId: 1
      name: common
      folder: common
      interval: 30s
      rules:
        - uid: de8nslt2boni8b
          title: UP 모니터링
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                disableTextWrap: false
                editorMode: builder
                expr: up
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 30s
          isPaused: false
          notification_settings:
            receiver: Slack
    - orgId: 1
      name: redis
      folder: redis
      interval: 1m
      rules:
        - uid: ee8nx3rzsbpxce
          title: '낮은 키 히트율: 키 히트율이 50% 미만으로 떨어질 경우'
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: ae8kbj16ie96of
              model:
                editorMode: code
                expr: "(\r\n  rate(redis_keyspace_hits_total[5m]) /\r\n  (rate(redis_keyspace_hits_total[5m]) + rate(redis_keyspace_misses_total[5m]))\r\n) * 100\r\n"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 50
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          isPaused: false
          notification_settings:
            receiver: Slack
```
